version: 2 # CircleCI version
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/repo
    steps:
      - checkout
      - run: ./.circleci.sh
  addons:
  sonarcloud:
    organization: "tijn167-github" # the key of the org you chose at step #3
  apt:
    packages:
      - oracle-java8-installer
  script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
